_name_: sine
data_dir: dataloaders/data/basic_waveforms/sine_200hz_small.npy
sample_len: 2048
min_freq: 200
max_freq: 200
num_frequencies: 1
num_random_amplitudes: 20
noise_amplitude: 0.1
overwrite_existing_file: False
val_split: 0.1