#defaults:
#  - dataset: mnist
#  - model: dummy
#  - optimizer: adam
#  - scheduler: plateau
#  - trainer: default
#  - task: classification
#  - loader: default

#train:
#  monitor: val/loss
#  mode: min

defaults:
  - /trainer: default
  - /loader: default
  - /dataset: cr_small
  - /task: regression
  - /optimizer: adamw
  - /scheduler: plateau
  - /model: sashimi

model:
  n_layers: 8
  expand: 2
  ff: 2
  pool:
    - 4
    - 4
  dropout: 0.0
  # prenorm: True
  # layer:
  #   n_ssm: 1

train:
  monitor: val/loss
  mode: min

task:
  metrics:
    - mse


loader:
  batch_size: 1

scheduler:
  patience: 20

trainer:
  max_epochs: 1000
