# @package _global_

defaults:
  - _self_
  #- dataset: mnist
  #- model: dummy
  #- optimizer: adam
  #- scheduler: plateau
  #- trainer: default
  #- task: classification
  #- loader: default
  - experiment: sashimi_sine

train:
  monitor: val/loss
  mode: min


